// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjZLCUD846ZyK0tgSAVqcfmCJTxG0kqY',
    appId: '1:454022500586:web:2a915bf957d69654b64793',
    messagingSenderId: '454022500586',
    projectId: 'loja-virtual-5ec1a',
    authDomain: 'loja-virtual-5ec1a.firebaseapp.com',
    storageBucket: 'loja-virtual-5ec1a.appspot.com',
    measurementId: 'G-854TH0HR6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIr-CfNHs-2k4zyP2Ae0O7u5lx4Q5d8w',
    appId: '1:454022500586:android:e86c3dba92fbcc9bb64793',
    messagingSenderId: '454022500586',
    projectId: 'loja-virtual-5ec1a',
    storageBucket: 'loja-virtual-5ec1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3KOw_UkPZ7E0O_5Go86LgIoMYcjlHT9s',
    appId: '1:454022500586:ios:a431eb690582e725b64793',
    messagingSenderId: '454022500586',
    projectId: 'loja-virtual-5ec1a',
    storageBucket: 'loja-virtual-5ec1a.appspot.com',
    iosClientId: '454022500586-26df2sr9i26cl5hirh82aqv92oacaguc.apps.googleusercontent.com',
    iosBundleId: 'br.com.softsantos.lojaVirtual',
  );
}
